import type { NextPage } from 'next'
import Head from 'next/head'
import { Container, Text, Grid, Spacer } from '@nextui-org/react'
import 'rc-slider/assets/index.css'
import LightsController from '../components/lights-controller'
import { PropertyIOProps } from '../components/property-io'

const musicProperties: Array<PropertyIOProps> = [
  {
    min: 1,
    max: 8,
    step: 1,
    defaultVal: 8,
    topic: 'lights/sl-music/mode',
    label: 'Mode',
  },
  {
    min: 0,
    max: 255,
    step: 1,
    defaultVal: 0,
    topic: 'lights/sl-music/minDim',
    label: 'Minimum Dim (0-255)',
  },
  {
    min: 0,
    max: 255,
    step: 1,
    defaultVal: 255,
    topic: 'lights/sl-music/maxDim',
    label: 'Maximum Dim (0-255)',
  },
  {
    min: 0,
    max: 60000,
    step: 250,
    defaultVal: 2000,
    topic: 'lights/sl-music/animTime',
    label: 'Animation Time (0-60000ms)',
  },
]

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Text h1>Hello.</Text>
        <Spacer y={2} />
        <Grid.Container gap={2} justify="center">
          <Grid lg={4}>
            <LightsController
              title="Music Corner Lights"
              properties={musicProperties}
            />
          </Grid>
        </Grid.Container>
      </Container>
    </>
  )
}

export default Home
