import type { NextPage } from 'next'
import Head from 'next/head'
import { Container, Text, Button } from '@nextui-org/react'
import axios from 'axios'

const Home: NextPage = () => {
  async function handleClick() {
    const response = await axios.get('/api/test')
    console.log(response.data)
    alert('done')
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Text h1>Hello.</Text>
        <Button onClick={handleClick}>Click me</Button>
      </Container>
    </>
  )
}

export default Home
